channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cudatoolkit=11.1.1
  - krb5=1.19.4
  - ld_impl_linux-64=2.38
  - libcurl=7.87.0
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.46.0
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1s
  - pip=22.3.1
  - pycurl=7.45.1
  - python=3.8.16
  - readline=8.2
  - sqlite=3.40.1
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - aiofile==3.8.1
      - aiofiles==22.1.0
      - alabaster==0.7.13
      - antlr4-python3-runtime==4.8
      - anyio==3.6.2
      - argcomplete==2.0.0
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - attrs==22.2.0
      - babel==2.11.0
      - backcall==0.2.0
      - beautifulsoup4==4.11.2
      - bitarray==2.7.3
      - bleach==6.0.0
      - blosc2==2.0.0
      - boto3==1.26.63
      - botocore==1.29.63
      - botorch==0.8.2
      - bracex==2.3.post1
      - cachetools==5.3.0
      - caio==0.9.11
      - cffi==1.15.1
      - charset-normalizer==3.0.1
      - chemprop==1.5.2
      - click==8.1.3
      - cloudpickle==1.3.0
      - cmx==0.0.23
      - colorama==0.4.6
      - comm==0.1.2
      - contourpy==1.0.7
      - cvxopt==1.3.0
      - cycler==0.11.0
      - cython==0.29.33
      - debugpy==1.6.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.6
      - docutils==0.19
      - einops==0.6.0
      - executing==1.2.0
      - expandvars==0.9.0
      - fairseq==0.12.2
      - fastjsonschema==2.16.2
      - flask==2.2.2
      - fonttools==4.38.0
      - fqdn==1.5.1
      - functional-notations==0.5.2
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-api-core==2.11.0
      - google-api-python-client==2.76.0
      - google-auth==2.16.0
      - google-auth-httplib2==0.1.0
      - google-auth-oauthlib==0.4.6
      - google-cloud-core==2.3.2
      - google-cloud-storage==2.7.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.4.1
      - googleapis-common-protos==1.58.0
      - gpytorch==1.9.1
      - grpcio==1.51.3
      - h11==0.9.0
      - httpcore==0.11.1
      - httplib2==0.21.0
      - httptools==0.5.0
      - httpx==0.15.4
      - hydra-core==1.0.7
      - hyperopt==0.2.7
      - idna==3.4
      - imageio==2.25.0
      - imageio-ffmpeg==0.4.8
      - imagesize==1.4.1
      - importlib-metadata==6.0.0
      - importlib-resources==5.10.2
      - install==1.3.5
      - ipykernel==6.21.1
      - ipython==8.9.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.4
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jaynes==0.9.3
      - jedi==0.18.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.0.2
      - jupyter-console==6.4.4
      - jupyter-core==5.2.0
      - jupyter-events==0.6.3
      - jupyter-http-over-ws==0.0.8
      - jupyter-server==2.2.1
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.4
      - lazy-loader==0.1rc2
      - linear-operator==0.3.0
      - lxml==4.9.2
      - markdown==3.4.1
      - markupsafe==2.1.2
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.6
      - mistune==2.0.4
      - ml-logger==0.9.4
      - more-itertools==9.0.0
      - mpmath==1.3.0
      - msgpack==1.0.5
      - multidict==4.7.6
      - multipledispatch==0.6.0
      - mypy-extensions==0.4.3
      - nbclassic==0.5.1
      - nbclient==0.7.2
      - nbconvert==7.2.9
      - nbformat==5.7.3
      - nest-asyncio==1.5.6
      - networkx==2.8.8
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - numexpr==2.8.4
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - omegaconf==2.0.6
      - opt-einsum==3.3.0
      - packaging==23.0
      - pandas==1.5.3
      - pandas-flavor==0.3.0
      - pandocfilters==1.5.0
      - params-proto==2.10.6
      - parso==0.8.3
      - pbr==5.11.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.4.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==2.6.2
      - portalocker==2.7.0
      - pot==0.9.0
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.36
        # protobuf==3.19.6
      - protobuf
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - py4j==0.10.9.7
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.21
        # pyg-lib==0.1.0+pt113cu117
      - https://data.pyg.org/whl/torch-1.13.0%2Bcu117/pyg_lib-0.1.0%2Bpt113cu117-cp38-cp38-linux_x86_64.whl
      - pygments==2.14.0
      - pyparsing==3.0.9
      - pyro-api==0.1.2
      - pyro-ppl==1.8.4
      - pyrsistent==0.19.3
      - pysmiles==1.0.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.4
      - pytz==2022.7.1
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==25.0.0
      - qtconsole==5.4.0
      - qtpy==2.3.0
      - rdkit==2022.9.3
      - regex==2022.10.31
      - requests==2.28.2
      - requests-futures==1.0.0
      - requests-oauthlib==1.3.1
      - requests-toolbelt==0.10.1
      - rfc3339-validator==0.1.4
      - rfc3986==1.5.0
      - rfc3986-validator==0.1.1
      - rsa==4.9
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.7
      - s3transfer==0.6.0
      - sacrebleu==2.3.1
      - sanic==20.9.0
      - sanic-cors==0.10.0.post3
      - sanic-plugins-framework==0.9.5
      - scikit-image==0.19.3
      - scikit-learn==1.2.1
      - scikit-video==1.1.11
      - scipy==1.10.0
      - seaborn==0.12.2
      - send2trash==1.8.0
      - setuptools==59.5.0
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - snowballstemmer==2.2.0
      - soupsieve==2.3.2.post1
      - sphinx==6.1.3
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - stack-data==0.6.2
      - sympy==1.11.1
      - tables==3.8.0
      - tabulate==0.9.0
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.5.1
      - termcolor==2.2.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tifffile==2023.2.2
      - tinycss2==1.2.1
      - torch==1.13.1
        # torch-cluster==1.6.0+pt113cu117
      - https://data.pyg.org/whl/torch-1.13.0%2Bcu117/torch_cluster-1.6.0%2Bpt113cu117-cp38-cp38-linux_x86_64.whl
      - torch-geometric==2.2.0
        # torch-scatter==2.1.0+pt113cu117
      - https://data.pyg.org/whl/torch-1.13.0%2Bcu117/torch_scatter-2.1.0%2Bpt113cu117-cp38-cp38-linux_x86_64.whl
        # torch-sparse==0.6.16+pt113cu117
      - https://data.pyg.org/whl/torch-1.13.0%2Bcu117/torch_sparse-0.6.16%2Bpt113cu117-cp38-cp38-linux_x86_64.whl
        # torch-spline-conv==1.2.1+pt113cu117
      - https://data.pyg.org/whl/torch-1.13.0%2Bcu117/torch_spline_conv-1.2.1%2Bpt113cu117-cp38-cp38-linux_x86_64.whl
      - torchaudio==0.13.1
      - torchdiffeq==0.2.2
      - torchvision==0.14.1
      - tornado==6.2
      - tqdm==4.64.1
      - traitlets==5.9.0
      - typed-argument-parser==1.7.2
      - typing==3.7.4.3
      - typing-extensions==4.4.0
      - typing-inspect==0.8.0
      - ujson==5.7.0
      - uri-template==1.2.0
      - uritemplate==4.1.1
      - urllib3==1.26.14
      - uvloop==0.17.0
        # warmup-scheduler==0.3.2
      - git+https://github.com/ildoonet/pytorch-gradual-warmup-lr.git
      - waterbear==2.6.6
      - wcmatch==8.4.1
      - wcwidth==0.2.6
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.5.0
      - websockets==8.1
      - werkzeug==2.2.2
      - widgetsnbextension==4.0.5
      - xarray==2023.1.0
      - zipp==3.12.0
